version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./apps:/apps
      - dev-static-data:/vol/web
    command: >
       sh -c "python manage.py wait_for_db &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000
              "
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=postgres
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}

    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  dev-db-data:
  dev-static-data:
